UCLALibrary/ftva-lab-data

- README.md
- docker_scripts/entrypoint.sh
- ftva_lab_data/fixtures/groups_and_permissions.json
- ftva_lab_data/management/commands/create_users_from_sheet.py
- ftva_lab_data/templates/add_edit_item.html
- ftva_lab_data/templates/registration/login.html
- ftva_lab_data/templates/view_item.html
- ftva_lab_data/tests.py
- ftva_lab_data/views.py
- project/urls.py
Implements [SYS-1841](https://uclalibrary.atlassian.net/browse/SYS-1841)
| **Acceptance Criteria** | **Notes** |
|--------|--------|
| ✅ There is an editors groups | The `editors` group is defined in the `groups_and_permissions.json` fixture, with appropriate permissions for adding and editing `SheetImport` objects assigned to it |
| ✅ The group and permission definitions are exported to a fixture | The `groups_and_permissions.json` fixture can be loaded via `python manage.py loaddata groups_and_permissions.json` |
| ✅ All editing functionality is restricted to users in the editors group | This is accomplished using the `@permission_required` decorator on the `add_item` and `edit_item` views |
| ✅ All other functionality within the application is restricted to logged-in users | This is …
> SYS-1841: restrict editing, add login, and add user-creation script

- ftva_lab_data/templates/partials/search_results_table.html
- ftva_lab_data/templates/search_results.html
- ftva_lab_data/tests.py
- ftva_lab_data/views.py
- static/css/style.css
- static/js/main.js
Fixes [SYS-1864](https://uclalibrary.atlassian.net/browse/SYS-1846)
The bulk of this fix is in lines 43 and 49 of `search_results_table.html`, and line 141 of `views.py`. These changes allow the pagination buttons to pass the name of the column to be searched, as well as the search term and page number.
To test in browser, attempt to replicate the scenario [described in the ticket](https://uclalibrary.atlassian.net/browse/SYS-1846) (search in a column, page back and forth) and observe that the results do not change.
There is a new test case here, which does usefully test search results split across two pages. However, it does not simulate the results of actually clicking on the buttons in the UI - instead, requests with specific parameter values are sent manually. So this test doesn't …
> SYS-1864: pagination bug fix

- ftva_lab_data/templates/view_item.html
- ftva_lab_data/tests.py
- ftva_lab_data/views.py
- ftva_lab_data/views_utils.py
Implements [SYS-1843](https://uclalibrary.atlassian.net/browse/SYS-1843)
Updates views and templates to hide fields with no values on the "View Item" display, as in the below screenshot.
To support this, the `view_item.html` template now expects as context a collection of dicts corresponding to different areas of the display: `header_info`, `storage_info`, `file_info`, `inventory_info`, and `advanced_info`. These dicts are created by the new `get_item_display_dicts()` function in `views_utils.py`. This PR includes a simple test for this function.
[SYS-1843]: https://uclalibrary.atlassian.net/browse/SYS-1843?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SYS-1843: Hide empty fields on View Item screen

- docker_scripts/entrypoint.sh
- ftva_lab_data/templates/base.html
- ftva_lab_data/templates/partials/search_results_table.html
- ftva_lab_data/templates/search_results.html
- static/css/style.css
Fixes [SYS-1854](https://uclalibrary.atlassian.net/browse/SYS-1854)
Through application of Bootstrap CSS classes and one small custom CSS change, several updates to the search results screen:
* Each column now has a fixed width as a percentage of the total table width. Column sizes should not change as filters are changed and pages are navigated.
* Instead of truncating, I opted to wrap text. I noticed that a number of filenames have distinguishing features only near the end of the name (e.g. "M190540_HTD10_104_R1191_MonroeSitsOutMillersTrial_**CaptureFiles_HD_ProRes4444**" vs. "M190540_HTD10_104_R1191_MonroeSitsOutMillersTrial_**Final_HD_ProRes4444**", which might be hidden behind truncation at smaller screen sizes. 
* Left and right margins on the table are reduced.
* Navigation buttons …
> SYS-1854: fix search result column widths, plus other styling improvements

- ftva_lab_data/templates/partials/search_results_table.html
Fixes [SYS-1858](https://uclalibrary.atlassian.net/browse/SYS-1858)
Fixes the bootstrap CSS class on the Assign column of the search results display. Checkboxes should now be top-aligned, matching other data elements.
[SYS-1858]: https://uclalibrary.atlassian.net/browse/SYS-1858?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SYS-1858: fix Assign checkbox alignment

- .devcontainer/devcontainer.json
- .gitignore
- charts/prod-ftvalabdata-values.yaml
- ftva_lab_data/models.py
- ftva_lab_data/table_config.py
- ftva_lab_data/templates/partials/search_results_table.html
- ftva_lab_data/templates/search_results.html
- ftva_lab_data/tests.py
- ftva_lab_data/views.py
- ftva_lab_data/views_utils.py
Implements [SYS-1864](https://uclalibrary.atlassian.net/browse/SYS-1864).  Version set to `v0.9.1` for deployment.
This PR adds support for displaying and searching full user names, which was a bigger set of changes than I expected:
* Changed the "Assign to..." list of users to display full name instead of username, via built-in `User.get_full_name()`
* Added a calculated property `assigned_user_full_name` to `SheetImport`, to support display of full names for users assigned to those records
* Changed search results template to display the new `assigned_user_full_name`  property
* Changed views and supporting files to search against `assigned_user_full_name`
* Searches are done against the first name, last name, and username
* It's not worth the effort to add support for searching full …
> SYS-1864: Add support for full user names

- ftva_lab_data/templates/add_edit_item.html
- ftva_lab_data/templates/partials/search_results_table.html
- ftva_lab_data/templates/search_results.html
- ftva_lab_data/templates/view_item.html
- ftva_lab_data/tests.py
- ftva_lab_data/views.py
Implements [SYS-1870](https://uclalibrary.atlassian.net/browse/SYS-1870)
Adds new `search`, `search_column`, and `page` context values for the `view_item` and `search_results` templates. These allow the "Back to Search" button to return the user to the exact search screen seen before clicking on the item page.
Testing:
Perform a search with some combination of filters and page navigation. Click a "View" link to display a record. Click "Back to Results" and note that your search term, search column, and page number were preserved.
[SYS-1870]: https://uclalibrary.atlassian.net/browse/SYS-1870?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SYS-1870: Fix behavior of "Back to Search" button

- ftva_lab_data/management/commands/import_status_and_inventory_numbers.py
- ftva_lab_data/tests.py
- process_data.sh
Implements [SYS-1862](https://uclalibrary.atlassian.net/browse/SYS-1861)
Builds off work done in [SYS-1861](https://uclalibrary.atlassian.net/browse/SYS-1862). The management command `import_status_info` is renamed to `import_status_and_inventory_numbers`. This command supports two options, which can be combined: `-s` to import Status info, and `-i` to import inventory numbers.
If Inventory Numbers are updated, the output report will contain a new sheet with information about the before and after values for all items with a changed Inventory Number.
`process_data.sh` has been updated to import both Status and Inventory Number information with the complete data load. When running this, I see these results:
```
18938 records updated
359 rows returned more than one match
164 rows returned no …
```
> SYS-1862: Import inventory numbers

- charts/prod-ftvalabdata-values.yaml
- ftva_lab_data/templates/add_edit_item.html
- ftva_lab_data/tests.py
- static/css/style.css
- static/js/main.js
Implements [SYS-1873](https://uclalibrary.atlassian.net/browse/SYS-1873)
- ✅ Update the Add/Edit item display to visually show that Filename is a required field, using an asterisk or other indicator.
In the Add/Edit item view, labels for required fields now show a red asterisks and a tooltip on hover over the label. The tooltip is in addition to the default browser tooltip that displays on hover over the input element itself.
I replaced the `django-bootstrap` template element with HTML elements to have more control over the label attributes, as I wanted to use the Bootstrap tooltip documented [here](https://getbootstrap.com/docs/5.2/components/tooltips/). The tooltip requires a couple lines of JavaScript, and the asterisks gets appended by a new CSS class. Whether a field is required or …
> SYS-1873: Add visual indicator for required input fields

- ftva_lab_data/fixtures/item_statuses.json
- ftva_lab_data/views_utils.py
Implements [SYS-1881](https://uclalibrary.atlassian.net/browse/SYS-1881) (combined with [SYS-1882](https://uclalibrary.atlassian.net/browse/SYS-1882))
- ✅ A new status, “Needs review”, is added
- ✅ “Hard Drive Barcode ID” is moved to Advanced Fields
I went ahead and combined these two tickets, as SYS-1881 is a blocker for [SYS-1883](https://uclalibrary.atlassian.net/browse/SYS-1883). I simply added a status item to the `item_statuses` fixture and removed `hard_drive_barcode_id` from the basic fields list in the `view_utils` function that returns the fields split up into basic and advanced. Seems to have done the trick ⬇️ 
[SYS-1881]: https://uclalibrary.atlassian.net/browse/SYS-1881?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[SYS-1882]: …
> SYS-1881: Add status and move field

- ftva_lab_data/management/commands/clean_imported_data.py
Implements [SYS-1883](https://uclalibrary.atlassian.net/browse/SYS-1883)
- ✅ Records with inline notes in the path fields are labelled with the “Needs review” status
This pull request adds a function to the `clean_imported_data` management command which filters the `SheetImport` objects for records where the three path-like fields (`file_folder_name`, `sub_folder_name`, and `file_name`) have sub-strings between square brackets. Per discussion on Slack, we decided such sub-strings are most likely inline notes. The function then applies the new "Needs review" status to matching records.
I also went ahead and updated docstrings to our new preferred format in this management command.
I didn't create any unit tests; let me know if you think a unit test for the regex is necessary. The count of …
> SYS-1883: Update status for records with inline notes

- charts/prod-ftvalabdata-values.yaml
- ftva_lab_data/models.py
- ftva_lab_data/templates/search_results.html
- ftva_lab_data/tests.py
- ftva_lab_data/urls.py
- ftva_lab_data/views.py
- ftva_lab_data/views_utils.py
- requirements.txt
- static/js/main.js
Implements [SYS-1880](https://uclalibrary.atlassian.net/browse/SYS-1880)
Adds an "Export to Excel" button, visible to all signed-in users, that will export the current set of search results to an Excel file called `FTVA_DL_search_results_{timestamp}.xlsx`. The export file contains all fields associated with each `SheetImport` object, not just those visible on the search results screen.
Includes minor refactoring of `main.js` to re-use the `setOrUpdate()` function written for user assignment, and updated docstrings throughout `views.py` to use the new Sphinx markup style.
This PR adds `xlsxwriter` as a new dependency in `requirements.txt`. Rebuild the Django container to install this.
[SYS-1880]: https://uclalibrary.atlassian.net/browse/SYS-1880?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU …
> SYS-1880: Export search results

- charts/prod-ftvalabdata-values.yaml
- ftva_lab_data/templates/release_notes.html
- ftva_lab_data/templates/search_results.html
- ftva_lab_data/tests.py
- ftva_lab_data/views.py
- ftva_lab_data/views_utils.py
- requirements.txt
Implements [SYS-1891](https://uclalibrary.atlassian.net/browse/SYS-1891)
Makes two performance-focused changes to the Export functionality of the FTVA Digital Data app:
1. Refactors the helper function `format_data_for_export()` in `views_utils.py` to avoid calling `SheetImport.objects.get()` for every item in the output set. Instead, `prefetch_related` and `select_related` are used to only query the database once, and lookup dictionaries are used to minimize the logic that happens inside the main loop.
This change is responsible for most of the performance improvement I saw locally, bringing the time to export all records from 42 seconds to 22 seconds.
2. Returns a CSV file via a `StreamingHttpResponse` instead of a binary Excel file with a standard `HttpResponse`. 
This change bought me …
> SYS-1891: Improve export performance

- charts/prod-ftvalabdata-values.yaml
- ftva_lab_data/templates/release_notes.html
Fixes (hopefully) [SYS-1904](https://uclalibrary.atlassian.net/browse/SYS-1904).  Tagger as version `v1.0.4` for deployment.
This PR increases the memory limits for the Django pod when deployed to our Kubernetes environment.  Per advice from the infrastructure team, both the request (the minimum allocated) and the limit for memory have been set to 1Gi.  We won't know if this allows the full CSV export to run successfully until deployed.
[SYS-1904]: https://uclalibrary.atlassian.net/browse/SYS-1904?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SYS-1904: Increase memory allocation

- ftva_lab_data/management/commands/set_empty_location_status.py
- ftva_lab_data/tests.py
Implements [SYS-1938](https://uclalibrary.atlassian.net/browse/SYS-1938)
Adds a new management command, `set_empty_location_status`. This command finds all `SheetImport` objects where `hard_drive_location`, `carrier_a_location`, and `carrier_b_location` are all empty, and sets a status of "Invalid vault" on these items.
The logic implemented here (and described in the Jira ticket) has changed since last week - I confirmed with Thelma this morning that we want to use the original statement of the logic (For any record where Carrier A location AND Carrier B location AND Hard Drive location are null, mark Status as invalid vault), not the version from Thursday (For any record where both Carrier A location AND Carrier B location are null, OR Hard Drive location is null, mark Status as …
> SYS-1938: management command to set status for items with no locations

- charts/prod-ftvalabdata-values.yaml
- ftva_lab_data/templates/add_edit_item.html
- ftva_lab_data/templates/partials/pagination_controls.html
- ftva_lab_data/templates/partials/search_results_table.html
- ftva_lab_data/templates/release_notes.html
- ftva_lab_data/templates/search_results.html
- ftva_lab_data/templates/view_item.html
- ftva_lab_data/tests.py
- ftva_lab_data/views.py
- ftva_lab_data/views_utils.py
Fixes [SYS-1929](https://uclalibrary.atlassian.net/browse/SYS-1929)
This PR updates `views.py` to return an encoded version of the string entered in the search input, safe for use in URL query strings. This `url_encoded_search` is then passed to the relevant templates in the view contexts, and from there passed between pages in the URL query strings to address the bug caused by reserved characters (e.g. `&`, `+`, `#`, etc) in the search param.
No new automated tests. All 44 existing tests pass. Please manually confirm all the example searches described in the Jira issue yield the expected number of results, particularly when navigating from the item view to the table view via the "Back to Search" button.
**TL;DR**
HTMX offers a lot of convenience via attributes like …
> SYS-1929: Encode search to make safe for URL query strings

- Dockerfile
- docker-compose.yml
- requirements.txt
Implements [SYS-1924](https://uclalibrary.atlassian.net/browse/SYS-1924).  Local-only, no deployment needed.
This PR makes three small changes to the developer environment:
* Add `git` to the `django` container, so local packages can be installed by `pip` from Github.
* Add support for local secrets, for the development environment only.
* Add our new local `ftva_etl` package to `requirements.txt`.
`docker-compose.yml` now will load an optional local file, `.docker-compose_local_secrets.env`.  This can contain any local values which need to be available to the running `django` container, like API keys and other real values which need to be kept secret.  These will be handled securely in our production deployment environment, but cannot be in the GH repository.
This secrets file does not …
> SYS-1924: Add git and support for local env secrets

- ftva_lab_data/tests.py
- ftva_lab_data/urls.py
- ftva_lab_data/views.py
- ftva_lab_data/views_utils.py
Implements [SYS-1942](https://uclalibrary.atlassian.net/browse/SYS-1942)
Adds a new endpoint, `/records/<record_id:int>`, that retrieves JSON data for an individual `SheetImport` object.
The endpoint uses HTTP basic auth, and requires valid Django account credentials (username and password for an active user). To support this, I added a new `basic_auth_required` decorator, defined in `views_utils.py`.
Given that this data will be used outside of this application, I wasn't sure whether to include Status and Assigned User data in the output JSON. I opted to include both for now.
Two simple success/failure tests are added in `tests.py`, for a total of 53: `python manage.py test`
[SYS-1942]: https://uclalibrary.atlassian.net/browse/SYS-1942?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA …
> SYS-1942: add record retrieval endpoint w/HTTP basic auth

- ftva_lab_data/tests.py
- ftva_lab_data/views.py
- ftva_lab_data/views_utils.py
Implements [SYS-1944](https://uclalibrary.atlassian.net/browse/SYS-1944)
Adds a new view, `get_alma_data()`. This view accepts an inventory number, which is used to get bib data from the Alma SRU interface. Bib data is processed to limit data to the [fields specified by FTVA staff](https://uclalibrary.atlassian.net/wiki/spaces/pm/pages/1305214995/Digital+Data+Preview+fields). The view returns a list of dicts, one for each Alma record, with the following structure:
* `record_id`: bib MMS id, from MARC 001.
* `title`: Work title, taken from MARC 245 by Pymarc `.title`.
* `full_data`: a dict with keys of the form "Field XYZ #n" for repeated fields, and "Field XYZ" for single fields. Values are the full content of the MARC field as a string excluding subfield delimiters, as presented by …
> Sys 1944/get alma data

- ftva_lab_data/views.py
- ftva_lab_data/views_utils.py
- project/settings.py
Implements [SYS-1945](https://uclalibrary.atlassian.net/browse/SYS-1945)
This PR adds a new view function: `get_filemaker_data()`. The function accepts an inventory number and returns a list of objects which include Filemaker records matching that inventory number. Only the specific fields that FTVA defined are returned in the `full_data` field of the search result object.
The function mimics the `get_alma_data()` view @ztucker4 added earlier. One difference is that FM credentials are loaded from environment variables using `os.getenv()` in `settings.py`. These are used to establish the FM client instance.
I wasn't sure if I should add the 10-record limit here, or if we'd prefer to do that in `ftva-etl`, so I left that off for now.
I opted not to "prettify" the keys returned in the …
> SYS-1945: Retrieve FM records for an inventory number

- ftva_lab_data/templates/external_search_results.html
- ftva_lab_data/templates/partials/external_record_modal.html
Implements [SYS-1947](https://uclalibrary.atlassian.net/browse/SYS-1947)
This PR adds a record detail modal to the external search results display. The user can now click on the `View Record` button(s) within the external search results table and launch a modal with the key-value pairs for that record displayed in a scrollable overlay, provided by Bootstrap.
Markup for all the modals is loaded with the initial page load. This should be acceptable for the number of records we're dealing with, keeping all data provided by a single view function and reducing the need to involve HTMX. It does however push some logic into the template. I think it is an acceptable amount of logic in the template, mostly just involving for loops. The modal markup is loaded using Django's `{% include %}`, passing …
> SYS-1947: Add record details modal to external search results view

- ftva_lab_data/urls.py
- ftva_lab_data/views.py
- ftva_lab_data/views_utils.py
Implements [SYS-1949](https://uclalibrary.atlassian.net/browse/SYS-1949)
This PR adds a view to generate a combined metadata record in JSON, using records retrieved from Alma, Filemaker, and Django. The view takes in a `record_id` referring to the Django record to use as the "base" for the metadata generation, then an `inventory_number` to use to retrieve records from Alma and Filemaker. If there is exactly one record each retrieved from Alma and Filemaker, these are joined with the Django record using the `get_mams_metadata()` from the `ftva_etl` package. Otherwise, a message is returned.
`TODO` notes are included for the return statements that will eventually render templates.
I didn't add any automated tests, but using the recent production data dump in a local instance, the following …
> SYS-1949: Add view to generate metadata JSON

- charts/Chart.yaml
- charts/prod-ftvalabdata-values.yaml
- charts/templates/externalsecret.yaml
- charts/values.yaml
- ftva_lab_data/templates/partials/metadata_modal.html
- ftva_lab_data/templates/partials/metadata_modal_content.html
- ftva_lab_data/templates/release_notes.html
- ftva_lab_data/templates/view_item.html
- ftva_lab_data/views.py
Implements [SYS-1950](https://uclalibrary.atlassian.net/browse/SYS-1950)
This PR adds a template to make use of the view added in SYS-1949 (#63). A template partial called `metadata_modal_content.html` is added, which is loaded by HTMX when the "View metadata" button is clicked on the view item page. HTMX swaps in the template partial to the modal added to `view_item.html`, which includes a loading indicator. Bootstrap handles the opening and styling of the modal. Successful requests which result in 1-1-1 records display the joined metadata as JSON (formatted in the view), while non-unique results show a warning message.
[SYS-1950]: https://uclalibrary.atlassian.net/browse/SYS-1950?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SYS-1950: Display metadata JSON

- charts/prod-ftvalabdata-values.yaml
- ftva_lab_data/templates/release_notes.html
- ftva_lab_data/tests.py
- ftva_lab_data/views_utils.py
Fixes [SYS-1977](https://uclalibrary.atlassian.net/browse/SYS-1977).  Tagged as `v1.0.10` for deployment.
This PR fixes a bug which prevented the JSON metadata from displaying.  The bug was caused by the `UUID()` data type being included in the Django dictionary generated by `views_utils.transform_record_to_dict()`.  The `uuid` field, which has a type of `UUID()`, could not be serialized to JSON by `json.dumps()`, raising a `TypeError`.
Since we only need the value and not the object itself, I cast `uuid` to a string, which fixes the bug.  I also added a test case to cover this.
`docker compose exec django python manage.py test` now runs 58 tests, all passing.
[SYS-1977]: https://uclalibrary.atlassian.net/browse/SYS-1977?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjo …
> SYS-1977: Fix metadata display bug caused by UUID

- .docker-compose_db.env
- .gitignore
- README.md
- docker_scripts/import_prod_db.sh
Implements [SYS-1983](https://uclalibrary.atlassian.net/browse/SYS-1983).  Development environment only, no deployment needed.
This PR adds support for importing production database dumps into the local development environment.  Documentation has been added to `README.md` in a new "Importing production database" section.
A few extra steps are needed here, the first time this is done: the development database user name and database name must be identical to production.  I've updated `.docker-compose_db.yml` to match.  This requires dropping your existing local database volume, to get rid of the old database and user names.
1. When ready, get a copy of the latest database dump from @akohler 
2. Shut down local system.
3. Delete database volume.
4. Start up local system and wait for database …
> SYS-1983: Add support for production database imports

- charts/prod-ftvalabdata-values.yaml
Change CPU resource limitation from `500m` (memory bounded) to `2` (cores).  Per @cachemeoutside this should allow the pod to allocate resources for burst activities, like complex database updates.
> Change CPU resource limit to remove memory limitation

- docker_scripts/import_prod_db.sh
Fixes [SYS-2028](https://uclalibrary.atlassian.net/browse/SYS-2028).  Developer only, no deployment needed.
This fixes a minor issue with the database import script, caused by a change in the database archive naming convention.  The script assumed that the name of the unpacked database directory was the same as the name of the archive itself, with the terminal `.tar.gz` removed.  The updated script now gets the name of the directory from within the archive, by doing a `tar tf archive_name` (to list the contents) and piping that to `head -1` to get the first entry, which is the directory name.
```
$ tar tf /tmp/pg_ftva-digital-data-2025-09-19.tar.gz
pg_ftva-digital-data-2025-09-19.d/  # <--- this is the directory name
pg_ftva-digital-data-2025-09-19.d/toc.dat …
```
> SYS-2028: Fix database import script
